name: CI

on:
  push:
    branches-ignore:
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '10.14.1'
      - name: npm install, build, and test
        run: |
          npm install
          npm run build
          npm test          
